name: Suggest a System Design Problem
description: Propose a new system to design
labels: ["suggestion"]
body:
  - type: textarea
    id: problem
    attributes:
      label: System Design Problem
      description: Describe the system you'd like to see designed.
      placeholder: "Example - Design a scalable chat application"
    validations:
      required: true
